### PR TITLE
Add support for AMD

### PR DESCRIPTION
**Pull request by asheshv**

### CODE REVIEW

**Comment by martindrapeau** [comment]
Your change works. However could you update the docs, the section about Installation?

**Comment by asheshv** [comment]
I committed one more change in my repository related to memory leaks.

Current implementation generates number of controls (View), but - never release them.
Hence - it generates the memory leak.

In the second commit, I have:
- Introduced a new class Backform.View (extended version of Backbone.View), which has close function to take care of the memory leaks.
- Used it as base class for Backform.Form and Backform.Control instead of Backbone.View.
- User needs to call 'close' function of Form to take care of the memory leaks in general.
- 'close' function calls onClose callback for user to do their own stuff.

Related to the change of documentation, and installation page.
- Where can I find them? Are you referring to README and index.html?

**Comment by martindrapeau** [comment]
index.html contains the docs. Its a static page which appears on the github site.
I will merge your pull request - you can update the docs in your subsequent one. The change you are making sounds nice. Can't wait to see it.

**Comment by asheshv** [comment]
Thanks.

**Pull request merged**
