### PR TITLE
Revert "Add support for AMD"

### PR DESCRIPTION
**Pull request by martindrapeau**
Reverts AmiliaApp/backform#19

I merged this pull request to rapidly. The AMD commit is good. Please create another pull request for that. However your other commit breaks Backform. The render method cannot be changed that way. You can override the remove method of the Backbone instead.

### CODE REVIEW

**Comment by asheshv** [comment]
Hmm...

Can you please also give some more details about - what exactly is broken?
So that - I can work on it. (An example will be helpful.)

1. I avoid overriding the Backbone methods, so that - if someday Backbone comes up with the same method, we do not override them.

2. We're not keeping track of the controls, which were created earlier.
And, that causes the memory leak.

Please refer to these links:
https://paydirtapp.com/blog/backbone-in-practice-memory-management-and-event-bindings/
http://andrewhenderson.me/tutorial/how-to-detect-backbone-memory-leaks/

**Comment by martindrapeau** [comment]
I do see the memory leak now. Controls are never removed upon re-rendering. Is that right?

In such a case, there is a simpler solution which doesn't break backwards compatibility. You can simply call the control's remove method. That performs the proper cleanup. Here is the potential code that is much simpler. Can you try this and let me know what you think?

```
initialize: function(options) {
  if (!(options.fields instanceof Backbone.Collection))
    options.fields = new Fields(options.fields || this.fields);
  this.fields = options.fields;
  this.model.errorModel = options.errorModel || this.model.errorModel || new Backbone.Model();
  this.controls = [];
},
cleanup: function() {
  _.each(this.controls, function() {
    control.remove();
  });
  this.controls.length = 0;
},
render: function() {
  this.cleanup();
  this.$el.empty();

  var form = this,
      $form = this.$el,
      model = this.model,
      controls = this.controls;

  this.fields.each(function(field) {
    var control = new (field.get("control"))({
      field: field,
      model: model
    });
    $form.append(control.render().$el);
    controls.push(control);
  });

  return this;
}
```

Note that if you want further cleanup, you can extend the base Control class' remove method and put that in there. It will always be called.

**Comment by asheshv** [comment]
Looks good that to me.
Apart from this - you may want to unbind the events registered in the controls (I believe)..

**Comment by martindrapeau** [comment]
As I said, a control is a view which already has a remove method that unlisten's to listenTo events. But you can override it if you want to do further cleanup (i.e. if you've used on instead of listenTo).
Would you like to integrate this code, test it and do a pull request?

**Comment by asheshv** [comment]
Sure.

**Comment by asheshv** [comment]
After some consideration - I've come up with this solution.
Please have a look at this patch.
```patch
diff --git a/src/backform.js b/src/backform.js
index 6b5008c..c5b6b7f 100644
--- a/src/backform.js
+++ b/src/backform.js
@@ -87,13 +87,27 @@
         options.fields = new Fields(options.fields || this.fields);
       this.fields = options.fields;
       this.model.errorModel = options.errorModel || this.model.errorModel || new Backbone.Model();
+      this.controls = [];
+    },
+    cleanup: function() {
+      _.each(this.controls, function() {
+        control.remove();
+      });
+      this.controls.length = 0;
+    },
+    remove: function() {
+      /* First do the clean up */
+      this.cleanup();
+      Backbone.View.prototype.remove.apply(this, arguments);
     },
     render: function() {
+      this.cleanup();
       this.$el.empty();

       var form = this,
           $form = this.$el,
-          model = this.model;
+          model = this.model,
+          controls = this.controls;

       this.fields.each(function(field) {
         var control = new (field.get("control"))({
@@ -101,6 +115,7 @@
           model: model
         });
         $form.append(control.render().$el);
+        controls.push(control);
       });

       return this;
@@ -217,6 +232,14 @@
       if (this.model.errorModel instanceof Backbone.Model)
         this.listenTo(this.model.errorModel, "change:" + name, this.updateInvalid);
     },
+    remove: function() {
+      /* Stop listening the changes in the model and errorModel */
+      this.stopListening(this.model, "change:" + name, this.render);
+      if (this.model.errorModel instanceof Backbone.Model)
+        this.stopListening(this.model.errorModel, "change:" + name, this.updateInvalid);
+
+      Backbone.View.prototype.remove.apply(this, arguments);
+    },
     formatter: ControlFormatter,
     getValueFromDOM: function() {
       return this.formatter.toRaw(this.$el.find(".uneditable-input").text(), this.model);
```

**Comment by martindrapeau** [comment]
That looks perfect! Nice addition with overriding remove there. Make a pull request with that and I will merge it.

**Comment by asheshv** [comment]
Thanks.
Done - please do the needful.

**Pull request merged**
